# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_CLI2"
version = "3.2.0"
license = "CC0-1.0"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "Unix-style commandline parsing using a prototype command"
categories = ["Command Line"]
keywords = ["fortran", "parse", "commandline", "arguments"]
homepage = "https://github.com/urbanjost/M_CLI2.git"

# unit test program
test = [
   { name="test_ignorecase", source-dir="test", main="test_ignorecase.f90" },
   { name="test_lastonly", source-dir="test", main="test_lastonly.f90" },
   { name="test_strict", source-dir="test", main="test_strict.f90" },
   { name="runTests", source-dir="test", main="test_suite_M_CLI2.f90" }
   ]

# demo programs
executable = [
   { name="demo1", source-dir="example", main="demo1.f90" },
   { name="demo2", source-dir="example", main="demo2.f90" },
   { name="demo3", source-dir="example", main="demo3.f90" },
   { name="demo4", source-dir="example", main="demo4.f90" },
   { name="demo5", source-dir="example", main="demo5.f90" },
   { name="demo6", source-dir="example", main="demo6.f90" },
   { name="demo7", source-dir="example", main="demo7.f90" },
   { name="demo8", source-dir="example", main="demo8.f90" },
   { name="demo9", source-dir="example", main="demo9.f90" },
#  { name="demo10", source-dir="example", main="demo10.f90" },
   { name="demo12", source-dir="example", main="demo12.f90" },
   { name="demo13", source-dir="example", main="demo13.f90" },
   { name="demo14", source-dir="example", main="demo14.f90" },
   { name="demo15", source-dir="example", main="demo15.f90" },
   { name="demo16", source-dir="example", main="demo16.f90" },
#  { name="demo17", source-dir="example", main="demo17.f90" },
# sample programs extracted from manpages:
   { name="demo_set_mode",              source-dir="example/demos", main="demo_set_mode.f90" },
   { name="demo_set_args",              source-dir="example/demos", main="demo_set_args.f90" },
   { name="demo_get_args",              source-dir="example/demos", main="demo_get_args.f90" },
   { name="demo_get_args_fixed_size",   source-dir="example/demos", main="demo_get_args_fixed_size.f90" },
   { name="demo_get_args_fixed_length", source-dir="example/demos", main="demo_get_args_fixed_length.f90" },
   { name="demo_get_subcommand",        source-dir="example/demos", main="demo_get_subcommand.f90" },
   { name="demo_specified",             source-dir="example/demos", main="demo_specified.f90" },
   { name="demo_M_CLI2",                source-dir="example/demos", main="demo_M_CLI2.f90" }
]
[build]
#auto-executables = true
#auto-examples = false
#auto-tests = false
#PASSES#module-naming = true          # Use default naming convention

[install]
library=true

[library]
source-dir="src"
