M_CLI2: /home/urbanjs/venus/V600/github/M_CLI2/src/M_CLI2.f90 File Reference
M_CLI2.f90 File Reference
Data Types
type m_cli2::option
type m_cli2::dictionary
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args_fixed_size
interface m_cli2::get_args_fixed_length
interface m_cli2::get_args_fixed_length
interface m_cli2::str
interface m_cli2::locate
interface m_cli2::insert
interface m_cli2::replace
interface m_cli2::remove
interface m_cli2::cgets
interface m_cli2::dgets
interface m_cli2::igets
interface m_cli2::lgets
interface m_cli2::rgets
interface m_cli2::sgets
Modules
module m_cli2
NAME
M_CLI2(3fm) - [ARGUMENTS::M_CLI2] - command line argument parsing using a prototype command (LICENSE:PD)
SYNOPSIS
Functions/Subroutines
subroutine, private m_cli2::check_commandline (help_text, version_text)
NAME
check_commandline(3f) - [ARGUMENTS:M_CLI2]check command and process pre-defined options
subroutine, public m_cli2::set_args (prototype, help_text, version_text)
NAME
set_args(3f) - [ARGUMENTS:M_CLI2] command line argument parsing (LICENSE:PD)
subroutine, private m_cli2::prototype_to_dictionary (string)
NAME
prototype_to_dictionary(3f) - [ARGUMENTS:M_CLI2] parse user command and store tokens into dictionary (LICENSE:PD)
elemental impure logical function, public m_cli2::specified (key)
NAME
update(3f) - [ARGUMENTS:M_CLI2] update internal dictionary given keyword and value (LICENSE:PD)
SYNOPSIS
subroutine, private m_cli2::update (key, val)
subroutine, private m_cli2::wipe_dictionary ()
NAME
wipe_dictionary(3fp) - [ARGUMENTS:M_CLI2] reset private M_CLI2(3fm) dictionary to empty (LICENSE:PD)
SYNOPSIS
character(len=:) function, allocatable, private m_cli2::get (key)
NAME
get(3f) - [ARGUMENTS:M_CLI2] get dictionary value associated with key name in private M_CLI2(3fm) dictionary
SYNOPSIS
subroutine, private m_cli2::prototype_and_cmd_args_to_nlist (prototype)
NAME
prototype_and_cmd_args_to_nlist(3f) - [ARGUMENTS:M_CLI2] convert Unix-like command arguments to table (LICENSE:PD)
SYNOPSIS
subroutine m_cli2::cmd_args_to_dictionary (check)
subroutine ifnull ()
subroutine, public m_cli2::print_dictionary (header, stop)
NAME
print_dictionary(3f) - [ARGUMENTS:M_CLI2] print internal dictionary created by calls to set_args(3f) (LICENSE:PD)
SYNOPSIS
logical function m_cli2::strtok (source_string, itoken, token_start, token_end, delimiters)
subroutine m_cli2::get_fixedarray_class (keyword, generic, delimiters)
NAME
get_args(3f) - [ARGUMENTS:M_CLI2] return keyword values when parsing command line arguments (LICENSE:PD)
subroutine m_cli2::get_anyarray_l (keyword, larray, delimiters)
subroutine m_cli2::get_anyarray_d (keyword, darray, delimiters)
subroutine m_cli2::get_anyarray_i (keyword, iarray, delimiters)
subroutine m_cli2::get_anyarray_r (keyword, rarray, delimiters)
subroutine m_cli2::get_anyarray_x (keyword, xarray, delimiters)
subroutine m_cli2::get_anyarray_c (keyword, strings, delimiters)
subroutine m_cli2::get_fixed_length_any_size_cxxxx (keyword, strings, delimiters)
subroutine m_cli2::get_fixedarray_i (keyword, iarray, delimiters)
subroutine m_cli2::get_fixedarray_r (keyword, rarray, delimiters)
subroutine m_cli2::get_fixed_size_complex (keyword, xarray, delimiters)
subroutine m_cli2::get_fixedarray_d (keyword, darr, delimiters)
subroutine m_cli2::get_fixedarray_l (keyword, larray, delimiters)
subroutine m_cli2::get_fixedarray_fixed_length_c (keyword, strings, delimiters)
subroutine m_cli2::get_scalar_d (keyword, d)
subroutine m_cli2::get_scalar_real (keyword, r)
subroutine m_cli2::get_scalar_i (keyword, i)
subroutine m_cli2::get_scalar_anylength_c (keyword, string)
subroutine m_cli2::get_scalar_fixed_length_c (keyword, string)
subroutine m_cli2::get_scalar_complex (keyword, x)
subroutine m_cli2::get_scalar_logical (keyword, l)
integer function m_cli2::longest_command_argument ()
NAME
longest_command_argument(3f) - [ARGUMENTS:M_args] length of longest argument on command line (LICENSE:PD)
SYNOPSIS
subroutine m_cli2::journal (where, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, ga, gb, gc, gd, ge, gf, gg, gh, gi, gj, nospace)
character(len=:) function, allocatable m_cli2::msg_scalar (generic0, generic1, generic2, generic3, generic4, generic5, generic6, generic7, generic8, generic9, generica, genericb, genericc, genericd, generice, genericf, genericg, generich, generici, genericj, nospace)
NAME
str(3f) - [M_CLI2] converts any standard scalar type to a string (LICENSE:PD)
SYNOPSIS
subroutine print_generic (generic)
character(len=:) function, allocatable m_cli2::msg_one (generic0, generic1, generic2, generic3, generic4, generic5, generic6, generic7, generic8, generic9, nospace)
subroutine print_generic (generic)
elemental pure character(len(str)) function m_cli2::upper (str, begin, end)
NAME
upper(3f) - [M_CLI2:CASE] changes a string to uppercase (LICENSE:PD)
elemental pure character(len(str)) function m_cli2::lower (str, begin, end)
NAME
lower(3f) - [M_CLI2:CASE] changes a string to lowercase over specified range (LICENSE:PD)
subroutine m_cli2::a2i (chars, valu, ierr)
subroutine m_cli2::a2d (chars, valu, ierr, onerr)
subroutine m_cli2::split (input_line, array, delimiters, order, nulls)
NAME
split(3f) - [M_CLI2:TOKENS] parse string into an array using specified delimiters (LICENSE:PD)
subroutine m_cli2::crack_cmd (cmd, old, new, ierr)
NAME
replace_str(3f) - [M_CLI2:EDITING] function globally replaces one substring for another in string (LICENSE:PD)
character(len=:) function, allocatable m_cli2::replace_str (targetline, old, new, ierr, cmd, range)
character(len=:) function, allocatable m_cli2::quote (str, mode, clip)
NAME
quote(3f) - [M_CLI2:QUOTES] add quotes to string as if written with list-directed input (LICENSE:PD)
SYNOPSIS
character(len=:) function, allocatable m_cli2::unquote (quoted_str, esc)
NAME
unquote(3f) - [M_CLI2:QUOTES] remove quotes from string as if read with list-directed input (LICENSE:PD)
SYNOPSIS
character(len=:) function, allocatable m_cli2::i2s (ivalue, fmt)
character(len=:) function, allocatable m_cli2::merge_str (str1, str2, expr)
NAME
merge_str(3f) - [M_CLI2:LENGTH] pads strings to same length and then calls MERGE(3f) (LICENSE:PD)
logical function m_cli2::decodebase (string, basein, out_baseten)
NAME
character(len=length) function m_cli2::lenset (line, length)
NAME
lenset(3f) - [M_CLI2:LENGTH] return string trimmed or padded to specified length (LICENSE:PD)
subroutine m_cli2::value_to_string (gval, chars, length, err, fmt, trimz)
NAME
value_to_string(3f) - [M_CLI2:NUMERIC] return numeric string from a numeric value (LICENSE:PD)
subroutine m_cli2::trimzeros_ (string)
NAME
trimzeros_(3fp) - [M_CLI2:NUMERIC] Delete trailing zeros from numeric decimal string (LICENSE:PD)
SYNOPSIS
subroutine m_cli2::substitute (targetline, old, new, ierr, start, end)
NAME
substitute(3f) - [M_CLI2:EDITING] subroutine globally substitutes one substring for another in string (LICENSE:PD)
subroutine, private m_cli2::locate_c (list, value, place, ier, errmsg)
NAME
locate(3f) - [M_CLI2] finds the index where a string is found or should be in a sorted array (LICENSE:PD)
subroutine, private m_cli2::locate_d (list, value, place, ier, errmsg)
subroutine, private m_cli2::locate_r (list, value, place, ier, errmsg)
subroutine, private m_cli2::locate_i (list, value, place, ier, errmsg)
subroutine, private m_cli2::remove_c (list, place)
NAME
remove(3f) - [M_CLI2] remove entry from an allocatable array at specified position (LICENSE:PD)
subroutine, private m_cli2::remove_d (list, place)
subroutine, private m_cli2::remove_r (list, place)
subroutine, private m_cli2::remove_l (list, place)
subroutine, private m_cli2::remove_i (list, place)
subroutine, private m_cli2::replace_c (list, value, place)
NAME
replace(3f) - [M_CLI2] replace entry in a string array at specified position (LICENSE:PD)
subroutine, private m_cli2::replace_d (list, value, place)
subroutine, private m_cli2::replace_r (list, value, place)
subroutine, private m_cli2::replace_l (list, value, place)
subroutine, private m_cli2::replace_i (list, value, place)
subroutine, private m_cli2::insert_c (list, value, place)
NAME
insert(3f) - [M_CLI2] insert entry into a string array at specified position (LICENSE:PD)
subroutine, private m_cli2::insert_r (list, value, place)
subroutine, private m_cli2::insert_d (list, value, place)
subroutine, private m_cli2::insert_l (list, value, place)
subroutine, private m_cli2::insert_i (list, value, place)
subroutine m_cli2::dict_delete (self, key)
NAME
dict_delete(3f) - [M_CLI2] delete entry by name from an allocatable sorted string array if it is present (LICENSE:PD)
character(len=:) function, allocatable m_cli2::dict_get (self, key)
NAME
dict_get(3f) - [M_CLI2] get value of key-value pair in a dictionary given key (LICENSE:PD)
subroutine m_cli2::dict_add (self, key, value)
NAME
dict_add(3f) - [M_CLI2] add or replace a key-value pair in a dictionary (LICENSE:PD)
subroutine m_cli2::many_args (n0, g0, n1, g1, n2, g2, n3, g3, n4, g4, n5, g5, n6, g6, n7, g7, n8, g8, n9, g9, na, ga, nb, gb, nc, gc, nd, gd, ne, ge, nf, gf, ng, gg, nh, gh, ni, gi, nj, gj)
character(len=:) function, allocatable c (generic)
subroutine get_generic (name, generic)
integer function, public m_cli2::iget (n)
real function, public m_cli2::rget (n)
real(kind=dp) function, public m_cli2::dget (n)
character(len=:) function, allocatable, public m_cli2::sget (n)
complex function, public m_cli2::cget (n)
logical function, public m_cli2::lget (n)
integer function, dimension(:), allocatable m_cli2::igs (n)
real function, dimension(:), allocatable m_cli2::rgs (n)
real(kind=dp) function, dimension(:), allocatable m_cli2::dgs (n)
character(len=:) function, dimension(:), allocatable m_cli2::sgs (n)
complex function, dimension(:), allocatable m_cli2::cgs (n)
logical function, dimension(:), allocatable m_cli2::lgs (n)
integer function, dimension(:), allocatable m_cli2::ig ()
real function, dimension(:), allocatable m_cli2::rg ()
real(kind=dp) function, dimension(:), allocatable m_cli2::dg ()
logical function, dimension(:), allocatable m_cli2::lg ()
complex function, dimension(:), allocatable m_cli2::cg ()
character(len=:) function, dimension(:), allocatable m_cli2::sg ()
Variables
integer, parameter, private m_cli2::dp =kind(0.0d0)
character(len=:), dimension(:), allocatable, public m_cli2::unnamed
character(len=:), allocatable, public m_cli2::remaining
character(len=:), dimension(:), allocatable m_cli2::keywords
character(len=:), dimension(:), allocatable m_cli2::values
integer, dimension(:), allocatable m_cli2::counts
logical, dimension(:), allocatable m_cli2::present_in
logical m_cli2::g_keyword_single_letter =.true.
character(len=:), allocatable m_cli2::g_passed_in
logical m_cli2::g_remaining_on
logical m_cli2::g_remaining_option_allowed
character(len=:), allocatable m_cli2::g_remaining
Function/Subroutine Documentation
c()
character(len=:) function, allocatable many_args::c (class(*), intent(in) generic) private
get_generic()
subroutine many_args::get_generic (character(len=*), intent(in) name, class(*), intent(out) generic) private
ifnull()
subroutine cmd_args_to_dictionary::ifnull () private
References m_cli2::get(), m_cli2::update(), and m_cli2::upper().
print_generic() [1/2]
subroutine msg_scalar::print_generic (class(*), intent(in) generic) private
print_generic() [2/2]
subroutine msg_one::print_generic (class(*), dimension(:), intent(in), optional generic) private