M_CLI2: /home/urbanjs/venus/V600/github/ARGS/M_CLI2/src/xx.f90 File Reference
xx.f90 File Reference
Data Types
type m_cli2::option
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args
interface m_cli2::get_args_fixed_size
interface m_cli2::get_args_fixed_length
interface m_cli2::get_args_fixed_length
interface m_cli2::str
interface m_cli2::locate_
interface m_cli2::insert_
interface m_cli2::replace_
interface m_cli2::remove_
interface m_cli2::cgets
interface m_cli2::dgets
interface m_cli2::igets
interface m_cli2::lgets
interface m_cli2::rgets
interface m_cli2::sgets
Modules
module m_cli2
Functions/Subroutines
subroutine, private m_cli2::check_commandline (help_text, version_text)
subroutine default_help ()
subroutine, public m_cli2::set_args (prototype, help_text, version_text, string, prefix, ierr, errmsg)
character(len=:) function, allocatable, public m_cli2::get_subcommand ()
subroutine m_cli2::set_usage (keyword, description, value)
recursive subroutine, private m_cli2::prototype_to_dictionary (string)
elemental impure logical function, public m_cli2::specified (key)
subroutine, private m_cli2::update (key, val)
subroutine, private m_cli2::wipe_dictionary ()
character(len=:) function, allocatable, private m_cli2::get (key)
subroutine, private m_cli2::prototype_and_cmd_args_to_nlist (prototype, string)
subroutine m_cli2::expand_response (name)
subroutine m_cli2::get_prototype (name, prototype)
subroutine find_and_read_response_file (rname)
subroutine position_response ()
subroutine process_response ()
integer function m_cli2::fileopen (filename, message)
character(len=:) function, allocatable m_cli2::get_env (name, default)
character(len=:) function, allocatable m_cli2::join_path (a1, a2, a3, a4, a5)
character(len=:) function, allocatable m_cli2::get_name ()
character(:) function, allocatable m_cli2::basename (path, suffix)
character(len=1) function m_cli2::separator ()
subroutine m_cli2::cmd_args_to_dictionary ()
subroutine ifnull ()
logical function get_next_argument ()
logical function maybe_value ()
subroutine, public m_cli2::print_dictionary (header, stop)
logical function m_cli2::strtok (source_string, itoken, token_start, token_end, delimiters)
subroutine m_cli2::get_fixedarray_class (keyword, generic, delimiters)
subroutine m_cli2::get_anyarray_l (keyword, larray, delimiters)
subroutine m_cli2::get_anyarray_d (keyword, darray, delimiters)
subroutine m_cli2::get_anyarray_i (keyword, iarray, delimiters)
subroutine m_cli2::get_anyarray_r (keyword, rarray, delimiters)
subroutine m_cli2::get_anyarray_x (keyword, xarray, delimiters)
subroutine m_cli2::get_anyarray_c (keyword, strings, delimiters)
subroutine m_cli2::get_args_fixed_length_a_array (keyword, strings, delimiters)
subroutine m_cli2::get_fixedarray_i (keyword, iarray, delimiters)
subroutine m_cli2::get_fixedarray_r (keyword, rarray, delimiters)
subroutine m_cli2::get_fixed_size_complex (keyword, xarray, delimiters)
subroutine m_cli2::get_fixedarray_d (keyword, darr, delimiters)
subroutine m_cli2::get_fixedarray_l (keyword, larray, delimiters)
subroutine m_cli2::get_fixedarray_fixed_length_c (keyword, strings, delimiters)
subroutine m_cli2::get_scalar_d (keyword, d)
subroutine m_cli2::get_scalar_real (keyword, r)
subroutine m_cli2::get_scalar_i (keyword, i)
subroutine m_cli2::get_scalar_anylength_c (keyword, string)
elemental impure subroutine m_cli2::get_args_fixed_length_scalar_c (keyword, string)
subroutine m_cli2::get_scalar_complex (keyword, x)
subroutine m_cli2::get_scalar_logical (keyword, l)
integer function m_cli2::longest_command_argument ()
subroutine m_cli2::journal (where, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, ga, gb, gc, gd, ge, gf, gg, gh, gi, gj, sep)
character(len=:) function, allocatable m_cli2::msg_scalar (generic0, generic1, generic2, generic3, generic4, generic5, generic6, generic7, generic8, generic9, generica, genericb, genericc, genericd, generice, genericf, genericg, generich, generici, genericj, sep)
subroutine print_generic (generic)
character(len=:) function, allocatable m_cli2::msg_one (generic0, generic1, generic2, generic3, generic4, generic5, generic6, generic7, generic8, generic9, sep)
subroutine print_generic (generic)
character(:) function, allocatable m_cli2::upper (str)
character(:) function, allocatable m_cli2::lower (str)
subroutine m_cli2::a2i (chars, valu, ierr)
subroutine m_cli2::a2d (chars, valu, ierr, onerr)
subroutine m_cli2::split (input_line, array, delimiters, order, nulls)
subroutine m_cli2::crack_cmd (cmd, old, new, ierr)
character(len=:) function, allocatable m_cli2::replace_str (targetline, old, new, ierr, cmd, range)
character(len=:) function, allocatable m_cli2::quote (str, mode, clip)
pure character(len=:) function, allocatable m_cli2::unquote (quoted_str, esc)
logical function m_cli2::decodebase (string, basein, out_baseten)
character(len=length) function m_cli2::lenset (line, length)
subroutine, private m_cli2::locate_c (list, value, place, ier, errmsg)
subroutine, private m_cli2::remove_c (list, place)
subroutine, private m_cli2::remove_l (list, place)
subroutine, private m_cli2::remove_i (list, place)
subroutine, private m_cli2::replace_c (list, value, place)
subroutine, private m_cli2::replace_l (list, value, place)
subroutine, private m_cli2::replace_i (list, value, place)
subroutine, private m_cli2::insert_c (list, value, place)
subroutine, private m_cli2::insert_l (list, value, place)
subroutine, private m_cli2::insert_i (list, value, place)
subroutine m_cli2::many_args (n0, g0, n1, g1, n2, g2, n3, g3, n4, g4, n5, g5, n6, g6, n7, g7, n8, g8, n9, g9, na, ga, nb, gb, nc, gc, nd, gd, ne, ge, nf, gf, ng, gg, nh, gh, ni, gi, nj, gj)
character(len=:) function, allocatable c (generic)
subroutine get_generic (name, generic)
integer function, public m_cli2::iget (n)
real function, public m_cli2::rget (n)
real(kind=dp) function, public m_cli2::dget (n)
character(len=:) function, allocatable, public m_cli2::sget (n)
complex function, public m_cli2::cget (n)
logical function, public m_cli2::lget (n)
integer function, dimension(:), allocatable m_cli2::igs (n)
real function, dimension(:), allocatable m_cli2::rgs (n)
real(kind=dp) function, dimension(:), allocatable m_cli2::dgs (n)
character(len=:) function, dimension(:), allocatable m_cli2::sgs (n, delims)
complex function, dimension(:), allocatable m_cli2::cgs (n)
logical function, dimension(:), allocatable m_cli2::lgs (n)
integer function, dimension(:), allocatable m_cli2::ig ()
real function, dimension(:), allocatable m_cli2::rg ()
real(kind=dp) function, dimension(:), allocatable m_cli2::dg ()
logical function, dimension(:), allocatable m_cli2::lg ()
complex function, dimension(:), allocatable m_cli2::cg ()
character(len=:) function, dimension(:), allocatable m_cli2::sg ()
subroutine m_cli2::mystop (sig, msg)
function m_cli2::atleast (line, length, pattern)
subroutine m_cli2::locate_key (value, place)
elemental impure subroutine, public m_cli2::set_mode (key, mode)
Variables
integer, parameter, private m_cli2::dp =kind(0.0d0)
integer, parameter, private m_cli2::sp =kind(0.0)
character(len= *), parameter m_cli2::gen ='(*(g0))'
character(len=:), dimension(:), allocatable, public m_cli2::unnamed
character(len=:), dimension(:), allocatable, public m_cli2::args
character(len=:), allocatable, public m_cli2::remaining
character(len=:), dimension(:), allocatable, save m_cli2::keywords
character(len=:), dimension(:), allocatable, save m_cli2::shorts
character(len=:), dimension(:), allocatable, save m_cli2::values
integer, dimension(:), allocatable, save m_cli2::counts
logical, dimension(:), allocatable, save m_cli2::present_in
logical, dimension(:), allocatable, save m_cli2::mandatory
logical, save m_cli2::g_debug =.false.
logical, save m_cli2::g_underdash =.false.
logical, save m_cli2::g_ignorecase =.false.
logical, save m_cli2::g_strict =.false.
logical, save m_cli2::g_keyword_single_letter =.true.
character(len=:), allocatable, save m_cli2::g_passed_in
logical, save m_cli2::g_remaining_on
logical, save m_cli2::g_remaining_option_allowed
character(len=:), allocatable, save m_cli2::g_remaining
character(len=:), allocatable, save m_cli2::g_subcommand
character(len=:), allocatable, save m_cli2::g_stop_message
integer, save m_cli2::g_stop
logical, save m_cli2::g_quiet
character(len=:), allocatable, save m_cli2::g_prefix
logical, save, public m_cli2::cli_response_file =.false.
logical, save m_cli2::g_append
logical, save m_cli2::g_options_only
logical, save m_cli2::g_response
character(len=:), allocatable, save m_cli2::g_response_ignored
Function/Subroutine Documentation
c()
character(len=:) function, allocatable many_args::c (class(*), intent(in) generic) private
default_help()
subroutine check_commandline::default_help private
References m_cli2::g_passed_in, m_cli2::g_quiet, m_cli2::journal(), and m_cli2::replace_str().
find_and_read_response_file()
subroutine get_prototype::find_and_read_response_file (character(len=*), intent(in) rname) private
References m_cli2::fileopen(), m_cli2::g_debug, m_cli2::gen, m_cli2::get_env(), m_cli2::join_path(), position_response(), process_response(), and m_cli2::split().
get_generic()
subroutine many_args::get_generic (character(len=*), intent(in) name, class(*), intent(out) generic) private
get_next_argument()
logical function cmd_args_to_dictionary::get_next_argument private
ifnull()
subroutine cmd_args_to_dictionary::ifnull private
References m_cli2::get(), m_cli2::update(), and m_cli2::upper().
maybe_value()
logical function cmd_args_to_dictionary::maybe_value private
References m_cli2::get(), and m_cli2::locate_key().
position_response()
subroutine get_prototype::position_response private
References m_cli2::g_debug, and m_cli2::gen.
print_generic() [1/2]
subroutine msg_scalar::print_generic (class(*), intent(in) generic) private
print_generic() [2/2]
subroutine msg_one::print_generic (class(*), dimension(:), intent(in), optional generic) private
References m_cli2::mystop().
process_response()
subroutine get_prototype::process_response private
References m_cli2::g_options_only, m_cli2::gen, m_cli2::lower(), and m_cli2::split().